openapi: 3.0.0
info:
  title: Check Service API
  description: Provides the status of your services
  version: "1.0.0"
  contact:
    email: tnakad@my.bcit.ca
paths:
  /check:
    get:
      operationId: app.check_services
      responses:
        "200":
          description: OK - stats returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Check"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Check:
      required:
        - receiver
        - storage
        - processing
        - analyzer
      properties:
        receiver:
          type: string
          example: "Healthy"
        storage:
          type: string
          example: "Storage has 6 parking and 4 payment events"
        processing:
          type: string
          example: "Processing has 6 parking and 4 payment events"
        analyzer:
          type: string
          example: "Analyzer has 10 parking and 4 payment events"
